minimum_pre_commit_version: "3.0.0"

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/po-sen/keepline
    rev: v0.4.0
    hooks:
      - id: keepline-commit-msg
      - id: keepline-file-check
