" Generated by vim-plug
" 六  7/20 17:06:18 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Jenkinsfile-vim-syntax'].commit = '0d05729168ea44d60862f17cffa80024ab30bcc9'
silent! let g:plugs['fzf'].commit = '50fa90dfb8eab7f03a7602ea9c098b01ff7236e8'
silent! let g:plugs['fzf.vim'].commit = 'f7c7b44764a601e621432b98c85709c9a53a7be8'
silent! let g:plugs['indentLine'].commit = 'b96a75985736da969ac38b72a7716a8c57bdde98'
silent! let g:plugs['jsonc.vim'].commit = '6fb92460f9e50505c9b93181a00f27d10c9b383f'
silent! let g:plugs['molokai'].commit = 'c67bdfcdb31415aa0ade7f8c003261700a885476'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nginx.vim'].commit = 'cffaec54f0c7f9518de053634413a20e90eac825'
silent! let g:plugs['python-syntax'].commit = '2cc00ba72929ea5f9456a26782db57fb4cc56a65'
silent! let g:plugs['supertab'].commit = '8c638fe17b470f4a27554cdf8e641bafa5e2a7a4'
silent! let g:plugs['undotree'].commit = '56c684a805fe948936cda0d1b19505b84ad7e065'
silent! let g:plugs['vim-airline'].commit = '02894b6ef4752afd8579fc837aec5fb4f62409f7'
silent! let g:plugs['vim-airline-themes'].commit = 'a9aa25ce323b2dd04a52706f4d1b044f4feb7617'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-cpp-modern'].commit = '6916d2a08c736f806a33cba7752a449ef530549e'
silent! let g:plugs['vim-easy-align'].commit = '9815a55dbcd817784458df7a18acacc6f82b1241'
silent! let g:plugs['vim-fugitive'].commit = '0444df68cd1cdabc7453d6bd84099458327e5513'
silent! let g:plugs['vim-gitgutter'].commit = '7b0b5098e3e57be86bb96cfbf2b8902381eef57c'
silent! let g:plugs['vim-helm'].commit = 'ae1ebc160d2b9b90108477ab10df7a4fc501e358'
silent! let g:plugs['vim-javascript'].commit = 'c470ce1399a544fe587eab950f571c83cccfbbdc'
silent! let g:plugs['vim-markdown'].commit = 'a657e697376909c41475a686eeef7fc7a4972d94'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'

PlugUpdate!

