" Generated by vim-plug
" 六  5/25 12:53:30 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Jenkinsfile-vim-syntax'].commit = '0d05729168ea44d60862f17cffa80024ab30bcc9'
silent! let g:plugs['fzf'].commit = 'daa602422dc272cbec6b99bc7520262672ad7230'
silent! let g:plugs['fzf.vim'].commit = '19de6507ff2a7e551e23c5d6b1ab11b585268447'
silent! let g:plugs['indentLine'].commit = 'b96a75985736da969ac38b72a7716a8c57bdde98'
silent! let g:plugs['jsonc.vim'].commit = '6fb92460f9e50505c9b93181a00f27d10c9b383f'
silent! let g:plugs['molokai'].commit = 'c67bdfcdb31415aa0ade7f8c003261700a885476'
silent! let g:plugs['nerdtree'].commit = 'fbb71fcd90602e3ec77f40b864b5f9b437c496c5'
silent! let g:plugs['nginx.vim'].commit = 'cffaec54f0c7f9518de053634413a20e90eac825'
silent! let g:plugs['python-syntax'].commit = '2cc00ba72929ea5f9456a26782db57fb4cc56a65'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['undotree'].commit = '56c684a805fe948936cda0d1b19505b84ad7e065'
silent! let g:plugs['vim-airline'].commit = '16c1638f93f93fad41da8cb6eef2bcd8eed0a57a'
silent! let g:plugs['vim-airline-themes'].commit = 'a9aa25ce323b2dd04a52706f4d1b044f4feb7617'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-cpp-modern'].commit = '1e6d2b52e34f222f79ecf523643a794f9079d7bd'
silent! let g:plugs['vim-easy-align'].commit = '9815a55dbcd817784458df7a18acacc6f82b1241'
silent! let g:plugs['vim-fugitive'].commit = '4f59455d2388e113bd510e85b310d15b9228ca0d'
silent! let g:plugs['vim-gitgutter'].commit = 'e801371917e52805a4ceb1e93f55ed1fba712f82'
silent! let g:plugs['vim-helm'].commit = '9425cf68d2a73d2efbfd05ab3e8b80ffb5a08802'
silent! let g:plugs['vim-javascript'].commit = 'c470ce1399a544fe587eab950f571c83cccfbbdc'
silent! let g:plugs['vim-markdown'].commit = 'a657e697376909c41475a686eeef7fc7a4972d94'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'

PlugUpdate!

