" Generated by vim-plug
" 三  4/24 22:55:30 2024
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Jenkinsfile-vim-syntax'].commit = '0d05729168ea44d60862f17cffa80024ab30bcc9'
silent! let g:plugs['fzf'].commit = 'e352b6887849cb6c3c8ae1d98ed357f94273e90a'
silent! let g:plugs['fzf.vim'].commit = '45d96c9cb1213204479593236dfabf911ff15443'
silent! let g:plugs['indentLine'].commit = 'b96a75985736da969ac38b72a7716a8c57bdde98'
silent! let g:plugs['jsonc.vim'].commit = '6fb92460f9e50505c9b93181a00f27d10c9b383f'
silent! let g:plugs['molokai'].commit = 'c67bdfcdb31415aa0ade7f8c003261700a885476'
silent! let g:plugs['nerdtree'].commit = 'f3a4d8eaa8ac10305e3d53851c976756ea9dc8e8'
silent! let g:plugs['nginx.vim'].commit = 'cffaec54f0c7f9518de053634413a20e90eac825'
silent! let g:plugs['python-syntax'].commit = '2cc00ba72929ea5f9456a26782db57fb4cc56a65'
silent! let g:plugs['supertab'].commit = 'f0093ae12a9115498f887199809a6114659fc858'
silent! let g:plugs['undotree'].commit = '56c684a805fe948936cda0d1b19505b84ad7e065'
silent! let g:plugs['vim-airline'].commit = 'd9f42cb46710e31962a9609939ddfeb0685dd779'
silent! let g:plugs['vim-airline-themes'].commit = 'a9aa25ce323b2dd04a52706f4d1b044f4feb7617'
silent! let g:plugs['vim-commentary'].commit = 'c4b8f52cbb7142ec239494e5a2c4a512f92c4d07'
silent! let g:plugs['vim-cpp-modern'].commit = '1e6d2b52e34f222f79ecf523643a794f9079d7bd'
silent! let g:plugs['vim-easy-align'].commit = '9815a55dbcd817784458df7a18acacc6f82b1241'
silent! let g:plugs['vim-fugitive'].commit = 'dac8e5c2d85926df92672bf2afb4fc48656d96c7'
silent! let g:plugs['vim-gitgutter'].commit = '67ef116100b40f9ca128196504a2e0bc0a2753b0'
silent! let g:plugs['vim-helm'].commit = '86cc6766db60b8cc5731068d0c2111dee1f2b328'
silent! let g:plugs['vim-javascript'].commit = 'c470ce1399a544fe587eab950f571c83cccfbbdc'
silent! let g:plugs['vim-markdown'].commit = 'a657e697376909c41475a686eeef7fc7a4972d94'
silent! let g:plugs['vim-startify'].commit = '4e089dffdad46f3f5593f34362d530e8fe823dcf'

PlugUpdate!

