name: Test Intel
on:
  push:
    branches:
      - 'intel/**'
  pull_request:
    branches:
      - 'intel/**'
jobs:
  test:
    name: 'macOS'
    runs-on: 'macos-13'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Test make install
        run: make install
      - name: Test make update
        run: make update
      - name: Test make uninstall
        run: make uninstall
